config/routes.rb
Rails.application.routes.draw do

  get 'movies/search', 'movies#search'
  resources :movies, only: :create
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  resources :lists, only: [:show, :new, :create] do
    resources :bookmarks, only: [:create]
    resources :reviews, only: [:create]
  end
  resources :bookmarks, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates_uniqueness_of :movie_id, scope: [:list_id]
  validates :movie_id, presence: true
  validates :list_id, presence: true
  validates :comment, length: { minimum: 2 }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :photo, presence: true
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks


  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def create

    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    movie_params = params[:bookmark][:movie]
    movie = Movie.find_by(title: movie_params['title'])
    if movie.nil?
      movie = Movie.create(title: movie_params['title'], overview: movie_params['overview'], poster_url: movie_params['poster_url'])
    end
    @bookmark.movie = movie
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      @bookmarks = Bookmark.where(list_id: @list.id)
      render 'lists/show'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])

    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @bookmarks = Bookmark.where(list_id: @list.id)
    @movies = params[:movies] if params[:movies]
    @movie = Movie.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
require 'json'
require 'open-uri'

class MoviesController < ApplicationController
  def search
    query = params[:search][:query]
    movies = fetch_movies(query)
    # raise
    list_id = params[:search][:list_id]

    redirect_to list_path(list_id, movies: movies)
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url)
  end

  def fetch_movies(user_query)
    query = user_query.split(' ').join('+')
    url = "https://api.themoviedb.org/3/search/movie?api_key=#{ENV['OMDB_API_KEY']}&query=#{query}"
    search_results = URI.open(url).read
    results = JSON.parse(search_results)
    results['results'][0..4]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true%>
    <script type="text/javascript" src="/Users/danielmaile/code/DanMW91/rails-watch-list/app/javascript/controllers/modal_controller.js"></script>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <a class="navbar-brand" href="#">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" />
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "My Lists", root_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Messages</a>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <div class="cards-container">
    <% @lists.each do |list| %>
      <%= link_to list_path(list) do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key %>')">
        <%= list.name %>
      </div>
      <% end %>
    <% end %>
  </div>

<%= link_to "Add New List", new_list_path, class: "btn btn-primary" %>
</div>

app/views/lists/new.html.erb
<div class='form-div'>
<%= simple_form_for(@list) do |f| %>
<%= f.input :name %>
<%= f.input :photo, as: :file %>
<%= f.button :submit, class: "btn btn-primary" %>
<% end %>
</div>

app/views/lists/show.html.erb
<%= javascript_pack_tag 'modal' %>


<div class="list-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key %>')">
  <h1><%= @list.name %></h1>
</div>
<div class="container">

  <div class='cards-container'>
    <% if @bookmarks.empty? %>
      <h3>No Movies Yet!</h3>
    <%end%>
    <% @bookmarks.each do |bookmark| %>
    <% movie = Movie.find(bookmark.movie_id) %>
    <div class="card-product">
      <img src="https://image.tmdb.org/t/p/w500/<%=movie.poster_url%>" />
      <div class="card-product-infos">
        <h2><%= movie.title %></h2>
        <p ><%= movie.overview %></p>
        <p class='m-3'><i>- "<%= bookmark.comment %>"</i></p>
        <%= link_to "x", bookmark_path(bookmark), method: "delete", class: "card-del"%>
      </div>
    </div>
    <% end %>
  </div>



  <%= simple_form_for :search, url: movies_search_path, method: "GET", html: { class: 'form' } do |f| %>
    <%= f.input :query, label: 'Search for Movie', input_html: {value: ""} %>
    <%= f.hidden_field :list_id, value: @list.id %>
    <%= f.submit "Search", class: "btn btn-primary" %>
  <% end %>


  <div class="cards-container">
    <% if @movies  %>

      <% @movies.each_with_index do |movie, i| %>
        <div class="card-product">
          <img src="https://image.tmdb.org/t/p/w500/<%=movie['poster_path']%>" />
          <div class="card-product-infos">
            <h2><%= movie['title'] %></h2>
            <p ><%= movie['overview'] %></p>
            <%= simple_form_for [@list, @bookmark] do |f| %>
            <%= f.input :comment, input_html: {minlength: 6} %>

            <%= f.fields_for @movie do |m| %>
              <%= m.hidden_field :title, value: movie['title'] %>
              <%= m.hidden_field :overview, value: movie['overview'] %>
              <%= m.hidden_field :poster_url, value: movie['poster_path'] %>
            <% end %>
            <%= f.button :submit, class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/movies/search.html.erb
<h1>Movies#search</h1>
<p>Find me in app/views/movies/search.html.erb</p>